import urllib.request
import base64

url1 = "https://github.com/glzzjhn-byte.png"
req1 = urllib.request.Request(url1, headers={'User-Agent': 'Mozilla/5.0'})
with urllib.request.urlopen(req1) as response:
    b64_img1 = base64.b64encode(response.read()).decode('utf-8')
    img_src = f"data:image/png;base64,{b64_img1}"

gif_src = "https://i.makeagif.com/media/3-14-2024/o9Frsc.gif"

svg_template = (
    "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"650\" height=\"600\" viewBox=\"0 0 650 600\">\n"
    "  <defs>\n"
    "    <style>\n"
    "      @import url('https://fonts.googleapis.com/css2?family=Fira+Code&amp;display=swap');\n"
    "      text { font-family: 'Fira Code', Consolas, monospace; font-size: 14.5px; fill: #cccccc; }\n"
    "      .bg { fill: #0c0c0c; stroke: #444; stroke-width: 2; }\n"
    "      .cmd-text { fill: #ffffff; }\n"
    "\n"
    "      /* Timeline 1: !profile (0s to 3s) */\n"
    "      .reveal-mask { animation: reveal 1s steps(10, end) forwards; }\n"
    "      .cursor-move { animation: moveCursor 1s steps(10, end) forwards, hideCursor 0.1s forwards 1.5s; }\n"
    "      .output { opacity: 0; animation: appear 0.1s forwards 1.5s; }\n"
    "      .profile-pic { opacity: 0; transform-origin: 95px 180px; animation: fadeIn 1.5s forwards 1.8s; }\n"
    "      .cursor-wait { opacity: 0; animation: appear 0.1s forwards 1.5s, blink 1s step-end 2.5, hideCursor 0.1s forwards 4s; }\n"
    "\n"
    "      /* Timeline 2: !LoveLife (4s to 8s) */\n"
    "      .reveal-mask-2 { opacity: 0; animation: appear 0.1s forwards 4s, reveal 1s steps(9, end) forwards 4s; }\n"
    "      .cursor-move-2 { opacity: 0; animation: appear 0.1s forwards 4s, moveCursor 1s steps(9, end) forwards 4s, hideCursor 0.1s forwards 5.5s; }\n"
    "      .compile-text { opacity: 0; animation: appear 0.1s forwards 5.5s; }\n"
    "      .error-text { opacity: 0; animation: appear 0.1s forwards 7s; }\n"
    "\n"
    "      /* GIF Summon (8.5s) */\n"
    "      .gif-pic { opacity: 0; transform-origin: center; animation: slideUpFade 1.5s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards 8.5s; }\n"
    "      .cursor-final { opacity: 0; animation: appear 0.1s forwards 8.5s, blink 1s step-end infinite 8.5s; }\n"
    "\n"
    "      /* Keyframes */\n"
    "      @keyframes reveal { from { transform: translateX(0); } to { transform: translateX(95px); } }\n"
    "      @keyframes moveCursor { from { transform: translateX(0); } to { transform: translateX(95px); } }\n"
    "      @keyframes appear { to { opacity: 1; } }\n"
    "      @keyframes hideCursor { to { opacity: 0; } }\n"
    "      @keyframes fadeIn { from { opacity: 0; transform: scale(0.9); } to { opacity: 1; transform: scale(1); } }\n"
    "      @keyframes slideUpFade { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }\n"
    "      @keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }\n"
    "    </style>\n"
    "    <clipPath id=\"circle-clip\">\n"
    "      <circle cx=\"95\" cy=\"180\" r=\"65\" />\n"
    "    </clipPath>\n"
    "  </defs>\n"
    "\n"
    "  <!-- Terminal Window Background -->\n"
    "  <rect width=\"650\" height=\"600\" rx=\"6\" class=\"bg\" />\n"
    "  <path d=\"M0 6 a 6 6 0 0 1 6 -6 h 638 a 6 6 0 0 1 6 6 v 24 h -650 z\" fill=\"#2d2d2d\" />\n"
    "  <text x=\"15\" y=\"20\" fill=\"#fff\" font-size=\"12\">C:\\Windows\\System32\\cmd.exe</text>\n"
    "\n"
    "  <!-- SEQUENCE 1: !profile -->\n"
    "  <text x=\"15\" y=\"60\" class=\"cmd-text\">@glzzjhn-byte> <tspan fill=\"#00A2FF\">!profile</tspan></text>\n"
    "  <rect x=\"155\" y=\"45\" width=\"100\" height=\"20\" fill=\"#0c0c0c\" class=\"reveal-mask\" />\n"
    "  <text x=\"155\" y=\"60\" class=\"cmd-text cursor-move\">_</text>\n"
    "\n"
    "  <g class=\"output\">\n"
    "    <text x=\"190\" y=\"110\" fill=\"#fff\" font-weight=\"bold\" font-size=\"16\">John Gabriel Ronao</text>\n"
    "    <text x=\"190\" y=\"130\" fill=\"#888\">System User</text>\n"
    "    <text x=\"190\" y=\"150\" fill=\"#555\">========================================</text>\n"
    "    <text x=\"190\" y=\"175\"><tspan fill=\"#fff\" font-weight=\"bold\">Major:</tspan> Computer Engineering (3rd Year)</text>\n"
    "    <text x=\"190\" y=\"195\"><tspan fill=\"#fff\" font-weight=\"bold\">Age  :</tspan> 21 Years</text>\n"
    "    <text x=\"190\" y=\"215\"><tspan fill=\"#fff\" font-weight=\"bold\">Loc  :</tspan> Bicol, Philippines</text>\n"
    "    <text x=\"190\" y=\"235\"><tspan fill=\"#fff\" font-weight=\"bold\">Dev  :</tspan> Java, C++, Python, Luau</text>\n"
    "    <text x=\"190\" y=\"255\"><tspan fill=\"#fff\" font-weight=\"bold\">Tasks:</tspan> Forge IDE, NexusPOS, Roblox Dev</text>\n"
    "    <text x=\"15\" y=\"300\" class=\"cmd-text\">@glzzjhn-byte> <tspan class=\"cursor-wait\">_</tspan></text>\n"
    "  </g>\n"
    "\n"
    "  <!-- John Gabriel Profile Picture -->\n"
    "  <g class=\"profile-pic\">\n"
    "    <circle cx=\"95\" cy=\"180\" r=\"68\" fill=\"#555\" />\n"
    "    <image href=\"__IMG_SRC__\" x=\"30\" y=\"115\" height=\"130\" width=\"130\" clip-path=\"url(#circle-clip)\" />\n"
    "  </g>\n"
    "\n"
    "  <!-- SEQUENCE 2: !LoveLife -->\n"
    "  <text x=\"155\" y=\"300\" class=\"cmd-text reveal-mask-2\"><tspan fill=\"#00A2FF\">!LoveLife</tspan></text>\n"
    "  <rect x=\"155\" y=\"285\" width=\"100\" height=\"20\" fill=\"#0c0c0c\" class=\"reveal-mask-2\" />\n"
    "  <text x=\"155\" y=\"300\" class=\"cmd-text cursor-move-2\">_</text>\n"
    "\n"
    "  <!-- The Compile & Error Output (All Red) -->\n"
    "  <text x=\"15\" y=\"335\" fill=\"#f44336\" class=\"compile-text\">> Compiling relationship algorithms...</text>\n"
    "  <text x=\"15\" y=\"355\" fill=\"#f44336\" font-weight=\"bold\" class=\"error-text\">[FATAL ERROR] 0x404: Partner not found.</text>\n"
    "  <text x=\"15\" y=\"375\" fill=\"#f44336\" class=\"error-text\">> Initiating emergency anime fallback...</text>\n"
    "\n"
    "  <!-- SEQUENCE 3: GIF Appears on a New Line (No Circle Frame) -->\n"
    "  <g class=\"gif-pic\">\n"
    "    <image href=\"__GIF_SRC__\" x=\"15\" y=\"390\" width=\"300\" height=\"170\" preserveAspectRatio=\"xMinYMin meet\" />\n"
    "  </g>\n"
    "\n"
    "  <!-- Final Cursor Pushed to the Bottom -->\n"
    "  <text x=\"15\" y=\"585\" class=\"cmd-text error-text\">@glzzjhn-byte> <tspan class=\"cursor-final\">_</tspan></text>\n"
    "</svg>"
)

svg_content = svg_template.replace("__IMG_SRC__", img_src).replace("__GIF_SRC__", gif_src)

with open("animated_cmd.svg", "w") as file:
    file.write(svg_content)
print("Successfully generated animated_cmd.svg!")
