name: Update Maven Libraries

on:
  schedule:
    - cron: "0 1 * * *" # Runs an hour after your profile cards
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRORFILE_SUMMARY_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Fetch and Update README
        run: python update_maven.py
        
      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update Maven libraries" || exit 0
          git push
